### ISSUE TITLE
Cannot install berkshelf 8.0.13 and Chef 18 with Ruby 3.3.4

### ISSUE THREAD

**Issue by mitchellhenke** [chef/berkshelf#34]
## Description

If I define a Gemfile requiring both berkshelf `~> 8.0.13` and chef `~> 18.0` on Ruby 3.3.4, I get bundler fails to solve the required versions.

## Berkshelf Version
8.0.13

## Platform Version
macOS 14.6.1 (23G93)

## Replication Case

A Gemfile with the following fails:

```ruby
source 'https://rubygems.org'

ruby "~> 3.3.4"

gem 'berkshelf', '~> 8.0.13'
gem 'chef', '~> 18.0'
```

## Berks Output

```
Could not find compatible versions

Because berkshelf >= 8.0.13 depends on chef ~> 17.0
  and Gemfile depends on berkshelf ~> 8.0.13,
  chef ~> 17.0 is required.
So, because Gemfile depends on chef ~> 18.0,
  version solving has failed.
```

**Comment by tpowell-progress** [comment]
@mitchellhenke 👋 thanks for the confirmation. Waiting for CI confirmation before hopefully pushing an `~> 18.0` specific version

**Comment by tpowell-progress** [comment]
https://github.com/chef/berkshelf/pull/35 should cover.

**Comment by tpowell-progress** [comment]
Unfortunately, an automated process insisted on 8.0.15, but the 8.0.12 and 8.0.13 versions have been yanked due to breaking more than they fix

**Comment by tpowell-progress** [comment]
Confirmed that
```ruby
source 'https://rubygems.org'

ruby "~> 3.3.0"

gem 'berkshelf', '~> 8.0.15'
gem 'chef', '~> 18.0'
```

successfully bundle installs

**Comment by mitchellhenke** [comment]
Thank you!
